show-fixes = true

[lint]
select = ['ALL']
ignore = [
    'ANN401', # Any not allowed
    'D100', # requires a docstring at the top of every file
    'D104', # requires a docstring for public package definitions
    'D107', # requires docstring in __init__
    'D203', # conflict with D211
    'D212', # conflict with D213
    'FIX002', # disallows todo comments
    'COM812', # trailing comma, incompatible with formatter
    'ISC001', # disallows single line string concat, incompatible with formatter
    'RET504', # makes you not assign immediately before returning
    'SIM108', # don't need to push ternaries
    'TC001', # requires type-checking blocks
    'TC002', # requires type-checking blocks
    'TC003', # requires type-checking blocks
    'TD002', # requires an author in todo comments
    'TD003', # requires a link in todo comments
    'TID253', # requires lazy import of big packages
]

[lint.per-file-ignores]
"/**/tests/*" = [
    'S101', # disallows assert
    'ANN201', # requires return type annotation for public function
    'SLF001', # Allow accessing private members during tests
    'INP001' # "implicit namespace package" is invalid for pytest
]

[format]
docstring-code-format = true
